### ISSUE TITLE
Não deixar dados sensíveis como API_KEYS no .env

### ISSUE THREAD

**Issue by luiizHenCode** [OpenitDev/wifacil-backend#3]
Recomento adicionar o `.env`  no `.gitignore` e adicionar um `.env.exemple` no projeto só com as variáveis necessárias, e quando outra pessoa autorizada precisar rodar o projeto na maquina, o responsável pode passar as informações de forma privada.

**Comment by leonardo-amaral** [comment]
Pode deixar meu principe!
